apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    app: db
spec:
  containers:
  - name: mysql-container
    image: 345852704676.dkr.ecr.us-east-1.amazonaws.com/mysql:mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    ports:
    - containerPort: 3306
