apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  containers:
  - name: web-container
    image: 345852704676.dkr.ecr.us-east-1.amazonaws.com/webapp:webapp
    env:
    - name: BACKGROUND_COLOR
      value: blue
    - name: DBPWD
      value: pw
    - name: DBUSER
      value: root
    - name: DATABASE
      value: employees
    - name: DBHOST
      value: mysqlpod.sql.svc.cluster.local
    - name: DBPORT
      value: "3306"
    ports:
    - containerPort: 8080
