apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: web
spec:
  containers:
  - name: web-container
    image: 345852704676.dkr.ecr.us-east-1.amazonaws.com/webapp:webapp
    ports:
    - containerPort: 8080
